### ISSUE TITLE
Create new sky asset

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#151]

**Comment by justnilana** [comment]
![9B34BF54-25FE-45E7-84D7-C6F59AB3D0A9](https://user-images.githubusercontent.com/114269115/208068318-ac354794-400b-4fda-89d1-79e2ee979aeb.jpg)
![IMG_0216](https://user-images.githubusercontent.com/114269115/208068325-f5529324-badc-40f3-bace-f8cf4682883e.jpg)
