### ISSUE TITLE
Create fire VFX

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#156]

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/217949777-c7abea08-5c07-4921-b0a2-027b5740b67b.mp4

Fire particles are in! They have a bunch of properties that can be easily changed in the inspector (size, speed, color, etc)

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/217950971-48b79d82-54cd-454b-80e9-c935641eb0f3.mp4

showing off the editable properties in the inspector

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/218190429-c9c91caf-72d6-4f83-99d2-d36df21f9685.mp4

made a new texture and allowed it to work with some more stylized outlined fire sprites, following our inspiration of Okami
