### ISSUE TITLE
Add VFX for slicing and dicing enemies

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#57]

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/199649758-4321addc-6d32-4615-9add-8f39f628a86f.mp4

added dust particles on landing to get acquainted with using particles

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/200066165-acd5e154-d563-442b-88c0-47c94814f757.mp4

added hit effects and blood particles. not finalized yet. will keep working on it for the next week

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/201009238-1fede22e-e72b-4087-9508-ec69cfeec90e.mp4

added hitstop / slowmo on hit. REALLY adds to the effect. will tone it down a bit for normal attacks, but leave it variable so big attacks can cause Big slowmo
