### ISSUE TITLE
Add in air attack functionality to player controller

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#60]

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/202372106-5cf1d8a5-fc00-4bb5-b1b3-faa5c4d28ac7.mp4

air attacks are in! they still need hitboxes (karen will add those) but the animations play, and you can only do one air combo per jump.

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/202377460-4c553d93-3382-4ee2-bea7-e8ecd3437557.mp4

here it is with hitboxes
