### ISSUE TITLE
Attempt to recreate and fix player slide/controller drift issue

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#67]

**Comment by lanedhoward** [comment]
https://user-images.githubusercontent.com/95249796/202386238-619f3470-54d2-4514-af96-51ae6d89ac6f.mp4

changed the deadzones which hopefully fixed the drift issue. will keep an eye out during future playtesting.

also made it so moving the analogue stick only a little bit will make inari move at only a wwalking pace !
